version: '3'
services:
  api-produto:
    build:
      context: .
      args:
        - BUILD_CONFIGURATION=Debug
      dockerfile: Dockerfile
    image: tech-challenge-soat1-grp13-produto:latest
    restart: on-failure    
    ports:
      - "5273:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=User ID=fiap;Password=SenhaLocalProduto;Host=postgres-db-produto;Port=5432;Database=techChallengeProduto;Pooling=true;
    depends_on:
      - postgres-db-produto

  postgres-db-produto:
    hostname: postgres-compose
    image: postgres
    environment:
      POSTGRES_PASSWORD: "SenhaLocalProduto"
      POSTGRES_USER: fiap
      POSTGRES_DB: techChallengeProduto
    ports:
      - "15439:5432"
    volumes:
      - tech-challenge-soat1-grp13-db-data-produto:/var/lib/postgresql/data

volumes:
  tech-challenge-soat1-grp13-db-data-produto: