version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-challenge-soat1-grp13-produto:latest
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - postgres-db

  postgres-db:  
    hostname: postgres-compose
    image: postgres
    environment:
      POSTGRES_PASSWORD: "S3nh@L0c@lP40dut0"
      POSTGRES_USER: fiap
      POSTGRES_DB: techChallengeProduto
    ports:
      - "15433:5432"
    volumes:
      - tech-challenge-soat1-grp13-produto-db-data:/var/lib/postgresql/data

volumes:
  tech-challenge-soat1-grp13-produto-db-data: